CREATE TABLE account (
    acc_key BIGINT AUTO_INCREMENT PRIMARY KEY,
    balance DECIMAL(19,2) DEFAULT 0,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    currency_code VARCHAR(10) DEFAULT 'EUR',
    crypto_flag BOOLEAN DEFAULT FALSE
);
